name: Docker Image CI

on:
  push:
    branches: [ end-to-end2 ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name:  nubificus/jetson-inference
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildargs: TOKEN=${{ secrets.NBFC_BUILDER_TOKEN }}
        tags: e2e
