name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: [self-hosted, "${{ matrix.arch }}" ]

    strategy:
      matrix: 
        arch: [x86_64, aarch64]
      fail-fast: false

    steps:
    - uses: actions/checkout@main

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name:  nubificus/jetson-inference
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: ${{ matrix.arch }}
        dockerfile: Dockerfile.${{ matrix.arch }}

  create_manifest:
    runs-on: [self-hosted, aarch64]
    needs: build

    steps:
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create manifest
        run: |
          docker manifest rm nubificus/jetson-inference
          docker manifest create nubificus/jetson-inference:latest \
            --amend nubificus/jetson-inference:x86_64 \
            --amend nubificus/jetson-inference:aarch64
          docker manifest push nubificus/jetson-inference:latest
